version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3050:3050"
    environment:
      - PORT=3050
      - PGUSER=admin
      - PGPASSWORD=admin
      - PGHOST=postgres-docker
      - PGPORT=5432
      - PGDATABASE=postgres
    depends_on:
      - postgres-docker

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres-docker:
    image: postgres:15
    container_name: postgres-docker
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend:/docker-entrypoint-initdb.d
